### ISSUE TITLE
Filter Downloaded replays

### ISSUE THREAD

**Issue by dtracers** [RLBots/Saltie#61]
The ability to download and filter replays based on criteria
(model hash, version info, upload date)

**Comment by Sciguymjm** [comment]
Filters will be in the form `<url>/replays/list?<filter>=<value>&<filter>=<value>` where `<filter>` is the name of the column in the database.

**Comment by Sciguymjm** [comment]
Finished. Form is `GET /replays/list?<filter>=<value>&<filter>=<value>`  where `<filter>` is the name of the column in the database and `<value>` is the value.
