### ISSUE TITLE
Client side way to know if the server is responding correctly

### ISSUE THREAD

**Issue by dtracers** [RLBots/Saltie#63]
A heartbeat or something from the client to know if it will upload successfully

**Comment by Sciguymjm** [comment]
Requires checking if uploading is working; i.e. database is responding

**Comment by Sciguymjm** [comment]
Procedure is to test the server using its new URL (test upload). If that times out, test for a website like `google.com`. If that times out, it's the client's fault.

**Comment by Sciguymjm** [comment]
Finished. New url is `GET /upload/replay/test`.
